mybatis:
    mapper-locations: classpath:/mapper/*.xml
    # mybatis日志（控制台显示sql语句）
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




server:
    port: 8085
spring:

    datasource:
      # 如果存在多个数据源，监控的时候可以通过名字来区分开来
        name: mysql
      # 连接数据库的url
        url: jdbc:mysql://localhost:3306/sixqx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      # 连接数据库的账号
        username: root
      # 连接数据库的密码
        password: root
      # 使⽤druid数据源
        type: com.alibaba.druid.pool.DruidDataSource


        Jpa:
            hibernate:
                # 更新或创建数据表
                ddl-auto: update
            # 在控制台显示sql
            show-sql: true

            servlet:
                multipart:
                    enabled: true
                    # 上传文件总的最大值
                    max-request-size: 10MB
                    # 单个文件的最大值
                    max-file-size: 10MB




    #配置日志输出
logging:
    file:
        name: logscc
    level:
        root: info
    pattern:
        file: '%d{yyyy/MM/dd-HH:mm:ss} %-5level %logger:%L - %msg%n'
        console: '%d{yyyy/MM/dd-HH:mm:ss} %level %logger:%L - %msg%n'


